const state={tasks:[],jobs:[],activeJob:null,belowRows:[],belowColumns:[],targetDate:'',classificationDate:'',stockRows:[],stockColumns:[],stockSortColumn:'',stockSortDirection:'asc'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const api=async(url,options={})=>{const r=await fetch(url,{headers:{"Content-Type":"application/json"},...options});if(!r.ok)throw new Error((await r.json()).detail||"请求失败");return r.json()};
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function showView(name){$$('.view,.nav').forEach(x=>x.classList.remove('active'));$(`#${name}-view`).classList.add('active');$(`.nav[data-view="${name}"]`)?.classList.add('active')}
function dateText(value){if(!value)return"—";return value.replace('T',' ').slice(0,16)}
async function loadStatus(){const s=await api('/api/status');$('#stats').innerHTML=`<div class="stat"><span>股票池规模</span><b>${s.pool_count}</b><small>只标的</small></div><div class="stat"><span>已生成股票页面</span><b>${s.page_count}</b><small>个页面</small></div><div class="stat"><span>研报覆盖</span><b>${s.research_covered}</b><small>/ ${s.research_total}</small></div><div class="stat"><span>系统状态</span><b>READY</b><small>本地就绪</small></div>`;const names={stock_pool:'股票池',ranking:'选股明细',classification:'分类总表',tags:'产业标签',research:'研报快照',financial:'公司财务'};$('#file-grid').innerHTML=Object.entries(s.files).map(([k,f])=>`<div class="file"><span>${names[k]}</span><b title="${f.name}">${f.name}</b><small>${dateText(f.modified)} · ${f.size_mb} MB</small></div>`).join('')}
async function loadTasks(){state.tasks=await api('/api/tasks');const quick=['calculate_targets','below_ma200','rating','filter_ma20','filter_ma200','tags','daily_brief','stock_pages'];$('#quick-actions').innerHTML=quick.map(id=>{const t=state.tasks.find(x=>x.id===id);return `<button class="quick-card" onclick="runTask('${id}')"><b>${t.title}</b><span>${t.description}</span></button>`}).join('');const groups={};state.tasks.forEach(t=>(groups[t.category]??=[]).push(t));$('#task-groups').innerHTML=Object.entries(groups).map(([group,tasks])=>`<section class="task-group"><h3>${group}</h3><div class="task-grid">${tasks.map(taskCard).join('')}</div></section>`).join('')}
function taskCard(t){const opts=t.options.map(name=>name==='workers'||name==='max_stocks'||name==='snapshots'?`<label>${name}<input type="number" data-opt="${name}" value="${name==='workers'?8:name==='snapshots'?3:50}"></label>`:`<label><input type="checkbox" data-opt="${name}">${name}</label>`).join('');return `<article class="task-card" data-task="${t.id}"><div class="top"><h4>${t.title}</h4>${t.network?'<span class="net">需要联网</span>':''}</div><p>${t.description}</p><div class="task-status" data-task-status></div><footer>${opts}<button class="text-btn" onclick="runTask('${t.id}')">运行 →</button></footer></article>`}
async function runTask(id){try{const card=$(`.task-card[data-task="${id}"]`);const options={};card?.querySelectorAll('[data-opt]').forEach(el=>{options[el.dataset.opt]=el.type==='checkbox'?el.checked:Number(el.value)});const job=await api(`/api/tasks/${id}`,{method:'POST',body:JSON.stringify({options})});toast(`${job.title} 已加入运行队列`);state.activeJob=job.id;openDrawer(job);await loadJobs()}catch(e){toast(e.message)}}
async function loadJobs(){state.jobs=await api('/api/jobs');const recent=state.jobs.slice(0,5);$('#recent-jobs').innerHTML=recent.length?recent.map(j=>`<div class="job-row" onclick="selectJob('${j.id}')"><i class="${j.status}"></i><div><b>${j.title}</b><small>${statusName(j.status)} · ${progressText(j)} · ${dateText(j.started_at||j.created_at)}</small><div class="mini-track"><i style="width:${j.progress||0}%"></i></div></div>${['queued','running'].includes(j.status)?`<button class="stop-mini" onclick="cancelFromCard(event,'${j.id}')">终止</button>`:`<span>${j.return_code===null?'':`代码 ${j.return_code}`}</span>`}</div>`).join(''):'<div class="empty">还没有运行任务</div>';$$('[data-task]').forEach(card=>{const job=state.jobs.find(j=>j.task_id===card.dataset.task&&['queued','running'].includes(j.status));const status=card.querySelector('[data-task-status]');status.innerHTML=job?`<span>${statusName(job.status)}</span><b>${progressText(job)}</b><button class="stop-mini" onclick="cancelFromCard(event,'${job.id}')">终止</button><div><i class="${job.progress_measurable?'':'moving'}" style="width:${job.progress_measurable?(job.progress||0):35}%"></i></div>`:''});if(state.activeJob){const job=state.jobs.find(x=>x.id===state.activeJob);if(job)openDrawer(job,false);if(job&&['success','failed','cancelled'].includes(job.status)){loadStatus();loadOutputs();if(job.task_id==='below_ma200')loadBelowMa200();if(job.task_id==='calculate_targets')loadTargetHistory();if(job.task_id==='rating')loadClassificationHistory()}}}
function statusName(s){return({queued:'等待中',running:'运行中',success:'已成功',failed:'失败',cancelled:'已停止'})[s]||s}
function progressText(job){if(job.progress_measurable)return `${Math.round(job.progress||0)}%${job.progress_total?` · ${job.progress_current}/${job.progress_total}`:''}`;return job.status==='running'?'执行中':'0%'}
function selectJob(id){state.activeJob=id;const job=state.jobs.find(x=>x.id===id);if(job)openDrawer(job)}
function openDrawer(job,force=true){if(force)$('#drawer').classList.add('open');$('#job-state').textContent=statusName(job.status);$('#job-title').textContent=job.title;$('#job-meta').textContent=`${dateText(job.started_at||job.created_at)} · ${job.command.join(' ')}`;$('#progress-message').textContent=job.progress_message||statusName(job.status);$('#progress-value').textContent=progressText(job);const bar=$('#progress-bar');bar.style.width=job.progress_measurable?`${job.progress||0}%`:'35%';bar.classList.toggle('moving',job.status==='running'&&!job.progress_measurable);const log=$('#job-log');const content=job.logs.join('\n')||'等待日志输出……';if(log.textContent!==content){log.textContent=content;log.scrollTop=log.scrollHeight}$('#cancel-job').style.display=['queued','running'].includes(job.status)?'block':'none'}
async function cancelJob(){if(!state.activeJob)return;await api(`/api/jobs/${state.activeJob}/cancel`,{method:'POST'});toast('已发送停止请求');loadJobs()}
async function cancelFromCard(event,id){event.stopPropagation();try{await api(`/api/jobs/${id}/cancel`,{method:'POST'});toast('任务已终止');if(state.activeJob===id)state.activeJob=null;await loadJobs()}catch(e){toast(e.message)}}
async function loadOutputs(){const items=await api('/api/outputs');$('#output-grid').innerHTML=items.length?items.map(x=>`<a class="output" target="_blank" href="/output/${encodeURI(x.path)}"><span>OPEN OUTPUT →</span><h3>${x.title}</h3><p>${x.name}<br>${dateText(x.modified)} · ${x.size_mb} MB</p></a>`).join(''):'<div class="empty">还没有可浏览的输出</div>'}
async function loadBelowMa200(){const data=await api('/api/previews/below-ma200');state.belowRows=data.rows;state.belowColumns=data.columns;$('#below-note').textContent=data.total?`${data.file.name} · 当前展示 ${data.columns.length} 个核心字段，原始CSV共 ${data.all_column_count} 列`:'尚未生成沪深_低于200日线.csv';$('#below-table thead').innerHTML=`<tr>${data.columns.map(c=>`<th>${escapeHtml(c)}</th>`).join('')}</tr>`;renderBelowRows()}
function renderBelowRows(){const query=$('#below-search').value.trim().toLowerCase();const rows=state.belowRows.filter(row=>!query||['代码','名称','所属行业'].some(key=>String(row[key]||'').toLowerCase().includes(query)));$('#below-table tbody').innerHTML=rows.length?rows.map(row=>`<tr>${state.belowColumns.map(c=>`<td>${escapeHtml(row[c])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${state.belowColumns.length||1}">没有匹配结果</td></tr>`;$('#below-count').textContent=`${rows.length} / ${state.belowRows.length} 只`}
async function loadTargetHistory(){const data=await api('/api/previews/target-count-history');const latest=data.latest||{};state.targetDate=latest['日期']||'';$('#target-date').textContent=state.targetDate;$('#strong-count').textContent=latest['强势数量']??'—';$('#recent-high-count').textContent=latest['近期新高数量']??'—';$('#history-high-count').textContent=latest['历史新高数量']??'—';$('#target-note').textContent=data.total?`${data.file.name} · 共记录 ${data.total} 个日期 · 点击数量查看股票`:'运行“计算标的”后生成数量历史';const names=['强势','近期新高','历史新高'];$('#target-history-body').innerHTML=data.rows.length?data.rows.map(row=>`<tr><td>${escapeHtml(row['日期'])}</td>${names.map(name=>`<td><button class="count-link" onclick="openStockList('target','${name}','${row['日期']}')">${escapeHtml(row[`${name}数量`])}</button></td>`).join('')}</tr>`).join(''):'<tr><td colspan="4">暂无历史记录</td></tr>'}
async function loadClassificationHistory(){const data=await api('/api/previews/classification-count-history');const latest=data.latest||{};const names=data.columns.slice(1).map(c=>c.replace(/数量$/,''));state.classificationDate=latest['日期']||'';$('#classification-date').textContent=state.classificationDate;$('#classification-summary').innerHTML=names.map(name=>`<button class="count-card" onclick="openStockList('classification','${name}')"><span>${escapeHtml(name)}</span><b>${escapeHtml(latest[`${name}数量`]??'—')}</b></button>`).join('');$('#classification-note').textContent=data.total?`${data.file.name} · 共记录 ${data.total} 个日期 · 点击数量查看股票`:'综合评级成功后生成分类数量历史';$('#classification-history-head').innerHTML=`<tr>${data.columns.map(c=>`<th>${escapeHtml(c)}</th>`).join('')}</tr>`;$('#classification-history-body').innerHTML=data.rows.length?data.rows.map(row=>`<tr><td>${escapeHtml(row['日期'])}</td>${names.map(name=>`<td><button class="count-link" onclick="openStockList('classification','${name}','${row['日期']}')">${escapeHtml(row[`${name}数量`])}</button></td>`).join('')}</tr>`).join(''):`<tr><td colspan="${data.columns.length}">暂无历史记录</td></tr>`}
async function openStockList(source,category,date=''){const selectedDate=date||(source==='target'?state.targetDate:state.classificationDate);if(!selectedDate){toast('暂无可查看的日期');return}try{const url=`/api/previews/stocks?source=${encodeURIComponent(source)}&category=${encodeURIComponent(category)}&date=${encodeURIComponent(selectedDate)}`;const data=await api(url);state.stockRows=data.rows;state.stockColumns=data.columns;state.stockSortColumn='';state.stockSortDirection='asc';$('#stock-list-title').textContent=`${category}股票明细`;$('#stock-list-subtitle').textContent=selectedDate;$('#stock-list-meta').textContent=data.file.path?`${data.file.name} · 共 ${data.total} 只 · 点击表头排序`:`该日期没有对应股票文件`;$('#stock-list-search').value='';renderStockHeader();renderStockRows();$('#stock-modal').classList.add('open')}catch(e){toast(e.message)}}
function renderStockHeader(){$('#stock-list-table thead').innerHTML=`<tr>${state.stockColumns.map(c=>{const active=state.stockSortColumn===c;const arrow=active?(state.stockSortDirection==='asc'?'▲':'▼'):'';return `<th><button class="sort-head ${active?'active':''}" onclick="sortStockList('${escapeHtml(c)}')"><span>${escapeHtml(c)}</span><i>${arrow||'↕'}</i></button></th>`}).join('')}</tr>`}
function sortStockList(column){if(state.stockSortColumn===column){state.stockSortDirection=state.stockSortDirection==='asc'?'desc':'asc'}else{state.stockSortColumn=column;state.stockSortDirection='asc'}renderStockHeader();renderStockRows()}
function stockSortValue(value){const text=String(value??'').trim();if(!text||['--','—','亏损','nan','none','null'].includes(text.toLowerCase()))return {missing:true,value:text};const cleaned=text.replace(/,/g,'').replace(/^[+]/,'');const match=cleaned.match(/^(-?\d+(?:\.\d+)?)\s*(%|万亿|亿|万)?$/);if(match){const unit={万:1e4,亿:1e8,万亿:1e12}[match[2]]||1;return {missing:false,value:Number(match[1])*unit,numeric:true}}return {missing:false,value:text,numeric:false}}
function renderStockRows(){const query=$('#stock-list-search').value.trim().toLowerCase();let rows=state.stockRows.filter(row=>!query||['代码','名称','所属行业'].some(key=>String(row[key]||'').toLowerCase().includes(query)));if(state.stockSortColumn){const column=state.stockSortColumn,direction=state.stockSortDirection==='asc'?1:-1;rows=rows.map((row,index)=>({row,index})).sort((a,b)=>{const av=stockSortValue(a.row[column]),bv=stockSortValue(b.row[column]);if(av.missing!==bv.missing)return av.missing?1:-1;if(av.missing&&bv.missing)return a.index-b.index;let result;if(av.numeric&&bv.numeric)result=av.value-bv.value;else result=String(av.value).localeCompare(String(bv.value),'zh-CN',{numeric:true,sensitivity:'base'});return result===0?a.index-b.index:result*direction}).map(item=>item.row)}$('#stock-list-table tbody').innerHTML=rows.length?rows.map(row=>`<tr>${state.stockColumns.map(c=>`<td>${escapeHtml(row[c])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${state.stockColumns.length||1}">暂无股票或没有匹配结果</td></tr>`;$('#stock-list-meta').dataset.filtered=rows.length}
function closeStockList(){$('#stock-modal').classList.remove('open')}
$$('.nav').forEach(x=>x.onclick=()=>showView(x.dataset.view));$$('[data-view-link]').forEach(x=>x.onclick=()=>showView(x.dataset.viewLink));$('#refresh').onclick=loadStatus;$('#refresh-targets').onclick=loadTargetHistory;$('#refresh-classifications').onclick=loadClassificationHistory;$('#refresh-below').onclick=loadBelowMa200;$('#below-search').oninput=renderBelowRows;$('#stock-list-search').oninput=renderStockRows;$('#close-stock-list').onclick=closeStockList;$('#stock-modal').onclick=event=>{if(event.target.id==='stock-modal')closeStockList()};$('#close-drawer').onclick=()=>$('#drawer').classList.remove('open');$('#cancel-job').onclick=cancelJob;
setInterval(()=>{$('#clock').textContent=new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())},1000);setInterval(loadJobs,1600);
Promise.all([loadStatus(),loadTasks(),loadJobs(),loadOutputs(),loadTargetHistory(),loadClassificationHistory(),loadBelowMa200()]).catch(e=>toast(e.message));
