const state={tasks:[],jobs:[],activeJob:null,targetDate:'',classificationDate:'',ruleComparison:null,stockRows:[],stockColumns:[],stockSortColumn:'',stockSortDirection:'asc',previewTables:{below:{rows:[],columns:[],sortColumn:'',sortDirection:'asc'},ma20:{rows:[],columns:[],sortColumn:'',sortDirection:'asc'},ma200:{rows:[],columns:[],sortColumn:'',sortDirection:'asc'}}};
const previewConfigs={below:{endpoint:'/api/previews/below-ma200',title:'低于200日线'},ma20:{endpoint:'/api/previews/nearby-ma/20',title:'20日均线附近'},ma200:{endpoint:'/api/previews/nearby-ma/200',title:'200日均线附近'}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const api=async(url,options={})=>{const r=await fetch(url,{headers:{"Content-Type":"application/json"},...options});if(!r.ok)throw new Error((await r.json()).detail||"请求失败");return r.json()};
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function showView(name){$$('.view,.nav').forEach(x=>x.classList.remove('active'));$(`#${name}-view`).classList.add('active');$(`.nav[data-view="${name}"]`)?.classList.add('active')}
function dateText(value){if(!value)return"—";return value.replace('T',' ').slice(0,16)}
async function loadStatus(){const s=await api('/api/status');$('#stats').innerHTML=`<div class="stat"><span>股票池规模</span><b>${s.pool_count}</b><small>只标的</small></div><div class="stat"><span>已生成股票页面</span><b>${s.page_count}</b><small>个页面</small></div><div class="stat"><span>研报覆盖</span><b>${s.research_covered}</b><small>/ ${s.research_total}</small></div><div class="stat"><span>系统状态</span><b>READY</b><small>本地就绪</small></div>`;const names={stock_pool:'股票池',ranking:'选股明细',classification:'分类总表',tags:'产业标签',zsxq:'知识星球观点',zsxq_audio:'知识星球语音',tuitui:'推推筛选结果',research:'研报快照',financial:'公司财务'};$('#file-grid').innerHTML=Object.entries(s.files).map(([k,f])=>`<div class="file"><span>${names[k]}</span><b title="${f.name}">${f.name}</b><small>${dateText(f.modified)} · ${f.size_mb} MB</small></div>`).join('');$('#latest-audio').innerHTML=audioPlayer(s.files.zsxq_audio)}
async function loadTasks(){state.tasks=await api('/api/tasks');const quick=['generate_top200','calculate_targets','clearance','zsxq','tts','below_ma200','rating','filter_ma20','filter_ma200','tuitui','tags','daily_brief','stock_pages'];$('#quick-actions').innerHTML=quick.map(id=>{const t=state.tasks.find(x=>x.id===id),monitor=id==='tuitui';return `<button class="quick-card" data-quick-task="${id}" onclick="runTask('${id}')"><b>${t.title}</b><span>${t.description}</span>${monitor?'<small data-monitor-action>开始持续监控 →</small>':''}</button>`}).join('');const groups={};state.tasks.forEach(t=>(groups[t.category]??=[]).push(t));$('#task-groups').innerHTML=Object.entries(groups).map(([group,tasks])=>`<section class="task-group"><h3>${group}</h3><div class="task-grid">${tasks.map(taskCard).join('')}</div></section>`).join('');syncMonitorControls()}
function taskCard(t){const defaults=t.id==='compare_rules'?{max_stocks:0,snapshots:30,step:5,horizons:'5'}:{workers:8,max_stocks:50,snapshots:3,step:20,horizons:'5,20,60',limit:5000,train_months:12,min_train_snapshots:24,interval:300};const opts=t.options.map(name=>{const kind=t.option_types?.[name]||'bool';if(kind==='bool')return `<label><input type="checkbox" data-opt="${name}">${name}</label>`;if(kind==='date')return `<label>${name}<input type="date" data-opt="${name}"></label>`;if(['int','positive_int','stock_limit'].includes(kind))return `<label>${name}<input type="number" data-opt="${name}" value="${defaults[name]??0}"></label>`;return `<label>${name}<input type="text" data-opt="${name}" value="${defaults[name]??''}"></label>`}).join('');const action=t.id==='tuitui'?'开始持续监控 →':'运行 →';return `<article class="task-card" data-task="${t.id}"><div class="top"><h4>${t.title}</h4>${t.network?'<span class="net">需要联网</span>':''}</div><p>${t.description}</p><div class="task-status" data-task-status></div><footer>${opts}<button class="text-btn" data-run-task onclick="runTask('${t.id}')">${action}</button></footer></article>`}
async function runTask(id){try{const card=$(`.task-card[data-task="${id}"]`);const options={};card?.querySelectorAll('[data-opt]').forEach(el=>{if(el.type!=='checkbox'&&!el.value.trim())return;options[el.dataset.opt]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value.trim()});const job=await api(`/api/tasks/${id}`,{method:'POST',body:JSON.stringify({options})});toast(id==='tuitui'?'持续监控已启动':`${job.title} 已加入运行队列`);state.activeJob=job.id;openDrawer(job);await loadJobs();syncMonitorControls()}catch(e){toast(e.message)}}
async function loadJobs(){state.jobs=await api('/api/jobs');const recent=state.jobs.slice(0,5);$('#recent-jobs').innerHTML=recent.length?recent.map(j=>`<div class="job-row" onclick="selectJob('${j.id}')"><i class="${j.status}"></i><div><b>${j.title}</b><small>${statusName(j.status)} · ${progressText(j)} · ${dateText(j.started_at||j.created_at)}</small><div class="mini-track"><i style="width:${j.progress||0}%"></i></div></div>${['queued','running'].includes(j.status)?`<button class="stop-mini" onclick="cancelFromCard(event,'${j.id}')">终止</button>`:`<span>${j.return_code===null?'':`代码 ${j.return_code}`}</span>`}</div>`).join(''):'<div class="empty">还没有运行任务</div>';$$('[data-task]').forEach(card=>{const job=state.jobs.find(j=>j.task_id===card.dataset.task&&['queued','running'].includes(j.status));const status=card.querySelector('[data-task-status]');status.innerHTML=job?`<span>${statusName(job.status)}</span><b>${progressText(job)}</b><button class="stop-mini" onclick="cancelFromCard(event,'${job.id}')">终止</button><div><i class="${job.progress_measurable?'':'moving'}" style="width:${job.progress_measurable?(job.progress||0):35}%"></i></div>`:''});if(state.activeJob){const job=state.jobs.find(x=>x.id===state.activeJob);if(job)openDrawer(job,false);if(job&&['success','failed','cancelled'].includes(job.status)){loadStatus();loadOutputs();if(job.task_id==='below_ma200')loadPreviewTable('below');if(job.task_id==='filter_ma20')loadPreviewTable('ma20');if(job.task_id==='filter_ma200')loadPreviewTable('ma200');if(job.task_id==='calculate_targets')loadTargetHistory();if(job.task_id==='rating')loadClassificationHistory();if(job.task_id==='compare_rules'&&job.status==='success')loadRuleComparison()}}}
function statusName(s){return({queued:'等待中',running:'运行中',success:'已成功',failed:'失败',cancelled:'已停止'})[s]||s}
function progressText(job){if(job.progress_measurable)return `${Math.round(job.progress||0)}%${job.progress_total?` · ${job.progress_current}/${job.progress_total}`:''}`;return job.status==='running'?'执行中':'0%'}
function selectJob(id){state.activeJob=id;const job=state.jobs.find(x=>x.id===id);if(job)openDrawer(job)}
function openDrawer(job,force=true){if(force)$('#drawer').classList.add('open');$('#job-state').textContent=statusName(job.status);$('#job-title').textContent=job.title;$('#job-meta').textContent=`${dateText(job.started_at||job.created_at)} · ${job.command.join(' ')}`;$('#progress-message').textContent=job.progress_message||statusName(job.status);$('#progress-value').textContent=progressText(job);const bar=$('#progress-bar');bar.style.width=job.progress_measurable?`${job.progress||0}%`:'35%';bar.classList.toggle('moving',job.status==='running'&&!job.progress_measurable);const log=$('#job-log');const content=job.logs.join('\n')||'等待日志输出……';if(log.textContent!==content){log.textContent=content;log.scrollTop=log.scrollHeight}$('#cancel-job').style.display=['queued','running'].includes(job.status)?'block':'none'}
async function cancelJob(){if(!state.activeJob)return;await api(`/api/jobs/${state.activeJob}/cancel`,{method:'POST'});toast('已发送停止请求');loadJobs()}
async function cancelFromCard(event,id){event.stopPropagation();try{await api(`/api/jobs/${id}/cancel`,{method:'POST'});toast('任务已终止');if(state.activeJob===id)state.activeJob=null;await loadJobs();syncMonitorControls()}catch(e){toast(e.message)}}
async function stopMonitor(id){try{await api(`/api/jobs/${id}/cancel`,{method:'POST'});toast('持续监控已终止');if(state.activeJob===id)state.activeJob=null;await loadJobs();syncMonitorControls()}catch(e){toast(e.message)}}
function syncMonitorControls(){const active=state.jobs.find(j=>j.task_id==='tuitui'&&['queued','running'].includes(j.status));const quick=$('[data-quick-task="tuitui"]');if(quick){quick.classList.toggle('monitor-running',!!active);quick.onclick=active?()=>stopMonitor(active.id):()=>runTask('tuitui');const action=quick.querySelector('[data-monitor-action]');if(action)action.textContent=active?'终止监控 ■':'开始持续监控 →'}const card=$('[data-task="tuitui"]');const run=card?.querySelector('[data-run-task]');if(run)run.style.display=active?'none':''}
function audioPlayer(file){if(!file?.path)return '<div class="empty">尚未生成语音，请先运行“知识星球转语音”</div>';const url=`/output/${encodeURI(file.path)}`;return `<div class="audio-card"><div><span>LATEST AUDIO</span><b>${escapeHtml(file.name)}</b><small>${dateText(file.modified)} · ${file.size_mb} MB</small></div><audio controls preload="metadata" src="${url}"></audio><a href="${url}" download>下载 MP3</a></div>`}
async function loadOutputs(){const items=await api('/api/outputs');$('#output-grid').innerHTML=items.length?items.map(x=>x.name.toLowerCase().endsWith('.mp3')?`<article class="output audio-output"><span>PLAY AUDIO</span><h3>${escapeHtml(x.title)}</h3>${audioPlayer(x)}</article>`:`<a class="output" target="_blank" href="/output/${encodeURI(x.path)}"><span>OPEN OUTPUT →</span><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.name)}<br>${dateText(x.modified)} · ${x.size_mb} MB</p></a>`).join(''):'<div class="empty">还没有可浏览的输出</div>'}
const percent=value=>value===null||value===undefined||value===''?'—':`${Number(value)>=0?'+':''}${(Number(value)*100).toFixed(2)}%`;
const ratio=value=>value===null||value===undefined||value===''?'—':`${(Number(value)*100).toFixed(1)}%`;
const qualityClass=value=>({高:'quality-high',中:'quality-medium',低:'quality-low'})[value]||'';
async function loadRuleComparison(){const data=await api('/api/previews/rule-comparison');state.ruleComparison=data;if(!data.available){$('#rule-summary').innerHTML='<div class="comparison-empty">尚未运行规则对比，请到任务中心执行“规则对比”。</div>';$('#rule-stability').innerHTML='';$('#rule-performance thead').innerHTML='';$('#rule-performance tbody').innerHTML='';$('#rule-note').textContent='';$('#rule-downloads').innerHTML='';return}const oldHorizon=$('#rule-horizon').value,oldPeriod=$('#rule-period').value;$('#rule-horizon').innerHTML=data.horizons.map(h=>`<option value="${h}">${h}日收益</option>`).join('');$('#rule-period').innerHTML=data.periods.map(p=>`<option value="${escapeHtml(p)}">${escapeHtml(p)}</option>`).join('');if(data.horizons.map(String).includes(oldHorizon))$('#rule-horizon').value=oldHorizon;if(data.periods.includes(oldPeriod))$('#rule-period').value=oldPeriod;const stats=data.statistics||{};$('#rule-summary').innerHTML=`<div class="rule-stat"><span>规则版本</span><b>${data.rules.length}</b><small>1个生产基线 + ${Math.max(0,data.rules.length-1)}个候选</small></div><div class="rule-stat"><span>历史截面</span><b>${data.snapshot_count}</b><small>${escapeHtml(data.snapshot_dates[0]||'—')} 至 ${escapeHtml(data.snapshot_dates.at(-1)||'—')}</small></div><div class="rule-stat"><span>统一股票样本</span><b>${stats.requested_stocks??'—'}</b><small>缺历史 ${stats.missing_history??0} · 分析失败 ${stats.analysis_failures??0}</small></div><div class="rule-stat"><span>截面间隔</span><b>${data.step??'—'}日</b><small>周期 ${data.horizons.join(' / ')} 日</small></div>`;$('#rule-note').textContent=`生成于 ${dateText(data.created_at)} · ${data.metadata_file.name} · 所有规则共用同一批信号和收益数据`;renderRuleComparison()}
function renderRuleComparison(){const data=state.ruleComparison;if(!data?.available)return;const selected=String($('#rule-horizon').value||data.horizons[0]),period=$('#rule-period').value||'总体';const descriptions=Object.fromEntries(data.rules.map(r=>[r.name,r.description]));$('#rule-stability').innerHTML=data.stability.map(row=>`<article class="rule-card"><header><div><span>${row['规则']==='baseline'?'PRODUCTION BASELINE':'CANDIDATE'}</span><h4>${escapeHtml(row['规则'])}</h4><p>${escapeHtml(descriptions[row['规则']]||'')}</p></div></header><div class="rule-metrics"><div><span>分类变化率</span><b>${ratio(row['分类变化率'])}</b></div><div><span>边界模糊率</span><b>${ratio(row['边界模糊率'])}</b></div><div><span>相对基线变化</span><b>${ratio(row['相对基线变化率'])}</b></div></div></article>`).join('');const rows=data.performance.filter(row=>String(row['周期'])===`${selected}日`&&row['样本区间']===period);const rules=data.rules.map(r=>r.name);const labels=[...new Set(rows.map(r=>r['分类']))].sort((a,b)=>String(a).localeCompare(String(b),'zh-CN'));$('#rule-performance thead').innerHTML=`<tr><th>分类</th>${rules.map(name=>`<th>${escapeHtml(name)}<br><small>${name==='baseline'?'生产基线':'候选规则'}</small></th>`).join('')}</tr>`;$('#rule-performance tbody').innerHTML=labels.map(label=>`<tr><td><b>${escapeHtml(label)}</b></td>${rules.map(name=>{const row=rows.find(x=>x['规则']===name&&x['分类']===label);if(!row)return '<td>—</td>';return `<td class="compare-cell"><b>${percent(row['平均同池超额'])} · 跑赢 ${ratio(row['跑赢同池率'])}</b><small>中位收益 ${percent(row['中位收益'])} · ${row['样本数']}样本/${row['覆盖截面数']}截面</small><small>${escapeHtml(row['统计结论']||'')}</small><small class="${qualityClass(row['可信度'])}">${escapeHtml(row['可信度'])}可信度 · ${escapeHtml(row['数据质量提示'])}</small></td>`}).join('')}</tr>`).join('');$('#rule-downloads').innerHTML=Object.entries(data.outputs).filter(([,file])=>file.path).map(([name,file])=>`<a href="/output/${encodeURI(file.path)}" target="_blank">${escapeHtml(name)} · ${escapeHtml(file.name)}</a>`).join('')}
async function loadPreviewTable(key){const config=previewConfigs[key],data=await api(config.endpoint),table=state.previewTables[key];table.rows=data.rows;table.columns=data.columns;table.sortColumn='';table.sortDirection='asc';$(`#${key}-note`).textContent=data.file.path?`${data.file.name} · 共 ${data.total} 只 · 当前展示 ${data.columns.length} 个核心字段，原始CSV共 ${data.all_column_count} 列 · 点击表头排序`:`尚未生成${config.title}结果`;$(`#${key}-search`).value='';renderPreviewHeader(key);renderPreviewRows(key)}
function renderPreviewHeader(key){const table=state.previewTables[key];$(`#${key}-table thead`).innerHTML=`<tr>${table.columns.map(c=>{const active=table.sortColumn===c,arrow=active?(table.sortDirection==='asc'?'▲':'▼'):'↕';return `<th><button class="sort-head ${active?'active':''}" data-sort-column="${escapeHtml(c)}" onclick="sortPreviewTable('${key}','${escapeHtml(c)}')"><span>${escapeHtml(c)}</span><i>${arrow}</i></button></th>`}).join('')}</tr>`}
function sortPreviewTable(key,column){const table=state.previewTables[key];if(table.sortColumn===column)table.sortDirection=table.sortDirection==='asc'?'desc':'asc';else{table.sortColumn=column;table.sortDirection='asc'}renderPreviewHeader(key);renderPreviewRows(key)}
function sortRows(rows,column,direction){if(!column)return rows;const multiplier=direction==='asc'?1:-1;return rows.map((row,index)=>({row,index})).sort((a,b)=>{const av=stockSortValue(a.row[column]),bv=stockSortValue(b.row[column]);if(av.missing!==bv.missing)return av.missing?1:-1;if(av.missing&&bv.missing)return a.index-b.index;let result;if(av.numeric&&bv.numeric)result=av.value-bv.value;else result=String(av.value).localeCompare(String(bv.value),'zh-CN',{numeric:true,sensitivity:'base'});return result===0?a.index-b.index:result*multiplier}).map(item=>item.row)}
function renderPreviewRows(key){const table=state.previewTables[key],query=$(`#${key}-search`).value.trim().toLowerCase();let rows=table.rows.filter(row=>!query||['代码','名称','所属行业'].some(field=>String(row[field]||'').toLowerCase().includes(query)));rows=sortRows(rows,table.sortColumn,table.sortDirection);$(`#${key}-table tbody`).innerHTML=rows.length?rows.map(row=>`<tr>${table.columns.map(c=>`<td>${escapeHtml(row[c])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${table.columns.length||1}">没有匹配结果</td></tr>`;$(`#${key}-count`).textContent=`${rows.length} / ${table.rows.length} 只`}
async function loadTargetHistory(){const data=await api('/api/previews/target-count-history');const latest=data.latest||{};state.targetDate=latest['日期']||'';$('#target-date').textContent=state.targetDate;$('#strong-count').textContent=latest['强势数量']??'—';$('#recent-high-count').textContent=latest['近期新高数量']??'—';$('#history-high-count').textContent=latest['历史新高数量']??'—';$('#target-note').textContent=data.total?`${data.file.name} · 共记录 ${data.total} 个日期 · 点击数量查看股票`:'运行“计算标的”后生成数量历史';const names=['强势','近期新高','历史新高'];$('#target-history-body').innerHTML=data.rows.length?data.rows.map(row=>`<tr><td>${escapeHtml(row['日期'])}</td>${names.map(name=>`<td><button class="count-link" onclick="openStockList('target','${name}','${row['日期']}')">${escapeHtml(row[`${name}数量`])}</button></td>`).join('')}</tr>`).join(''):'<tr><td colspan="4">暂无历史记录</td></tr>';renderTargetTrendChart(data)}
async function loadClassificationHistory(){const data=await api('/api/previews/classification-count-history');const latest=data.latest||{};const names=data.columns.slice(1).map(c=>c.replace(/数量$/,''));state.classificationDate=latest['日期']||'';$('#classification-date').textContent=state.classificationDate;$('#classification-summary').innerHTML=names.map(name=>`<button class="count-card" onclick="openStockList('classification','${name}')"><span>${escapeHtml(name)}</span><b>${escapeHtml(latest[`${name}数量`]??'—')}</b></button>`).join('');$('#classification-note').textContent=data.total?`${data.file.name} · 共记录 ${data.total} 个日期 · 点击数量查看股票`:'综合评级成功后生成分类数量历史';$('#classification-history-head').innerHTML=`<tr>${data.columns.map(c=>`<th>${escapeHtml(c)}</th>`).join('')}</tr>`;$('#classification-history-body').innerHTML=data.rows.length?data.rows.map(row=>`<tr><td>${escapeHtml(row['日期'])}</td>${names.map(name=>`<td><button class="count-link" onclick="openStockList('classification','${name}','${row['日期']}')">${escapeHtml(row[`${name}数量`])}</button></td>`).join('')}</tr>`).join(''):`<tr><td colspan="${data.columns.length}">暂无历史记录</td></tr>`;renderClassificationCharts(data)}
async function openStockList(source,category,date=''){const selectedDate=date||(source==='target'?state.targetDate:state.classificationDate);if(!selectedDate){toast('暂无可查看的日期');return}try{const url=`/api/previews/stocks?source=${encodeURIComponent(source)}&category=${encodeURIComponent(category)}&date=${encodeURIComponent(selectedDate)}`;const data=await api(url);state.stockRows=data.rows;state.stockColumns=data.columns;state.stockSortColumn='';state.stockSortDirection='asc';$('#stock-list-title').textContent=`${category}股票明细`;$('#stock-list-subtitle').textContent=selectedDate;$('#stock-list-meta').textContent=data.file.path?`${data.file.name} · 共 ${data.total} 只 · 点击表头排序`:`该日期没有对应股票文件`;$('#stock-list-search').value='';renderStockHeader();renderStockRows();$('#stock-modal').classList.add('open')}catch(e){toast(e.message)}}
function renderStockHeader(){$('#stock-list-table thead').innerHTML=`<tr>${state.stockColumns.map(c=>{const active=state.stockSortColumn===c;const arrow=active?(state.stockSortDirection==='asc'?'▲':'▼'):'';return `<th><button class="sort-head ${active?'active':''}" data-sort-column="${escapeHtml(c)}" onclick="sortStockList('${escapeHtml(c)}')"><span>${escapeHtml(c)}</span><i>${arrow||'↕'}</i></button></th>`}).join('')}</tr>`}
function sortStockList(column){if(state.stockSortColumn===column){state.stockSortDirection=state.stockSortDirection==='asc'?'desc':'asc'}else{state.stockSortColumn=column;state.stockSortDirection='asc'}renderStockHeader();renderStockRows()}
function stockSortValue(value){const text=String(value??'').trim();if(!text||['--','—','亏损','nan','none','null'].includes(text.toLowerCase()))return {missing:true,value:text};const cleaned=text.replace(/,/g,'').replace(/^[+]/,'');const match=cleaned.match(/^(-?\d+(?:\.\d+)?)\s*(%|万亿|亿|万)?$/);if(match){const unit={万:1e4,亿:1e8,万亿:1e12}[match[2]]||1;return {missing:false,value:Number(match[1])*unit,numeric:true}}return {missing:false,value:text,numeric:false}}
function renderStockRows(){const query=$('#stock-list-search').value.trim().toLowerCase();let rows=state.stockRows.filter(row=>!query||['代码','名称','所属行业'].some(key=>String(row[key]||'').toLowerCase().includes(query)));rows=sortRows(rows,state.stockSortColumn,state.stockSortDirection);$('#stock-list-table tbody').innerHTML=rows.length?rows.map(row=>`<tr>${state.stockColumns.map(c=>`<td>${escapeHtml(row[c])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${state.stockColumns.length||1}">暂无股票或没有匹配结果</td></tr>`;$('#stock-list-meta').dataset.filtered=rows.length}
function closeStockList(){$('#stock-modal').classList.remove('open')}
$$('.nav').forEach(x=>x.onclick=()=>showView(x.dataset.view));$$('[data-view-link]').forEach(x=>x.onclick=()=>showView(x.dataset.viewLink));$('#refresh').onclick=loadStatus;$('#refresh-targets').onclick=loadTargetHistory;$('#refresh-classifications').onclick=loadClassificationHistory;$('#refresh-rules').onclick=loadRuleComparison;$('#rule-horizon').onchange=renderRuleComparison;$('#rule-period').onchange=renderRuleComparison;Object.keys(previewConfigs).forEach(key=>{$(`#refresh-${key}`).onclick=()=>loadPreviewTable(key);$(`#${key}-search`).oninput=()=>renderPreviewRows(key)});$('#stock-list-search').oninput=renderStockRows;$('#close-stock-list').onclick=closeStockList;$('#stock-modal').onclick=event=>{if(event.target.id==='stock-modal')closeStockList()};$('#close-drawer').onclick=()=>$('#drawer').classList.remove('open');$('#cancel-job').onclick=cancelJob;
setInterval(()=>{$('#clock').textContent=new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())},1000);setInterval(()=>loadJobs().then(syncMonitorControls),1600);
Promise.all([loadStatus(),loadTasks(),loadJobs().then(syncMonitorControls),loadOutputs(),loadTargetHistory(),loadClassificationHistory(),loadRuleComparison(),...Object.keys(previewConfigs).map(loadPreviewTable)]).catch(e=>toast(e.message));
